#!/bin/sh 
export LM_LICENSE_FILE=7321@eclipse-lic-no.statoil.no
export F_UFMTENDIAN=big
export ARCH=`uname -m`
cd /project/eor/user/liuming/norne/opm-autodiff/build/bin/Bench_SPE3
/bin/rm -f ECL.CFG
/bin/cp /prog/ecl/grid/macros/CONFIG.ECL ./ECL.CFG 2>> BENCH_SPE3.ERR
executable=/prog/ecl/grid/2012.2/bin/linux_x86_64/eclipse.exe
$executable <<END 
BENCH_SPE3
BENCH_SPE3
30000000
30000000
$executable
END
mv -f /project/eor/user/liuming/norne/opm-autodiff/build/bin/Bench_SPE3/BENCH_SPE3.job /project/eor/user/liuming/norne/opm-autodiff/build/bin/Bench_SPE3/BENCH_SPE3.job.done
